### ISSUE TITLE
try to fintune

### ISSUE THREAD

**Issue by hotwa** [zjunlp/MolGen#19]
I miss this error in latest transformers：

```shell
[2024-12-17 09:36:00,382] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-17 09:36:03,777] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-12-17 09:36:03,778] [INFO] [runner.py:607:main] cmd = /home/lingyuzeng/micromamba/envs/molgen/bin/python3.10 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None generate_ds.py --dist 1 --gpu 1 --batch_size 30 --exp_name generate --exp_id qed --return_num 30 --max_len 100 --min_len 20 --top_k 30 --top_p 1 --beam 30 --process preprocess --generate_mode topk --checkpoint_path ../moldata/checkpoint/molgen.pkl --input_path ../moldata/pretrain/zinc250k.csv --output_path ../moldata/output/candidates.csv --finetune_path ../moldata/output/zinc250k_qed.csv --property qed --deepspeed --deepspeed_config generate_config.json
[2024-12-17 09:36:05,882] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-17 09:36:09,271] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2024-12-17 09:36:09,271] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=2, node_rank=0
[2024-12-17 09:36:09,271] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2024-12-17 09:36:09,271] [INFO] [launch.py:164:main] dist_world_size=2
[2024-12-17 09:36:09,272] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2024-12-17 09:36:09,272] [INFO] [launch.py:256:main] process 2564189 spawned with command: ['/home/lingyuzeng/micromamba/envs/molgen/bin/python3.10', '-u', 'generate_ds.py', '--local_rank=0', '--dist', '1', '--gpu', '1', '--batch_size', '30', '--exp_name', 'generate', '--exp_id', 'qed', '--return_num', '30', '--max_len', '100', '--min_len', '20', '--top_k', '30', '--top_p', '1', '--beam', '30', '--process', 'preprocess', '--generate_mode', 'topk', '--checkpoint_path', '../moldata/checkpoint/molgen.pkl', '--input_path', '../moldata/pretrain/zinc250k.csv', '--output_path', '../moldata/output/candidates.csv', '--finetune_path', '../moldata/output/zinc250k_qed.csv', '--property', 'qed', '--deepspeed', '--deepspeed_config', 'generate_config.json']
[2024-12-17 09:36:09,273] [INFO] [launch.py:256:main] process 2564190 spawned with command: ['/home/lingyuzeng/micromamba/envs/molgen/bin/python3.10', '-u', 'generate_ds.py', '--local_rank=1', '--dist', '1', '--gpu', '1', '--batch_size', '30', '--exp_name', 'generate', '--exp_id', 'qed', '--return_num', '30', '--max_len', '100', '--min_len', '20', '--top_k', '30', '--top_p', '1', '--beam', '30', '--process', 'preprocess', '--generate_mode', 'topk', '--checkpoint_path', '../moldata/checkpoint/molgen.pkl', '--input_path', '../moldata/pretrain/zinc250k.csv', '--output_path', '../moldata/output/candidates.csv', '--finetune_path', '../moldata/output/zinc250k_qed.csv', '--property', 'qed', '--deepspeed', '--deepspeed_config', 'generate_config.json']
[2024-12-17 09:36:11,507] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-17 09:36:11,514] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
| distributed init (rank 0): env://
| distributed init (rank 1): env://
[rank1]:[W1217 09:36:15.649690165 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
[rank0]:[W1217 09:36:16.864037670 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
BartForConditionalGeneration has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
INFO - 12/17/24 09:36:16 - 0:00:00 - ============ Initialized logger ============
INFO - 12/17/24 09:36:16 - 0:00:00 - The experiment will be stored in /home/lingyuzeng/project/MolGen/moldata/dump/1217-generate/BART_qed
                                     
INFO - 12/17/24 09:36:16 - 0:00:00 - Running command: python generate_ds.py --local_rank=0 --dist 1 --gpu 1 --batch_size 30 --exp_name generate --exp_id qed --return_num 30 --max_len 100 --min_len 20 --top_k 30 --top_p 1 --beam 30 --process preprocess --generate_mode topk --checkpoint_path '../moldata/checkpoint/molgen.pkl' --input_path '../moldata/pretrain/zinc250k.csv' --output_path '../moldata/output/candidates.csv' --finetune_path '../moldata/output/zinc250k_qed.csv' --property qed --deepspeed --deepspeed_config 'generate_config.json'

BartForConditionalGeneration has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/lingyuzeng/project/MolGen/MolGen/generate_ds.py", line 463, in <module>
[rank0]:     runner = Runner(cfgs, writer, logger, rank)
[rank0]:   File "/home/lingyuzeng/project/MolGen/MolGen/generate_ds.py", line 41, in __init__
[rank0]:     self.data_init()
[rank0]:   File "/home/lingyuzeng/project/MolGen/MolGen/generate_ds.py", line 45, in data_init
[rank0]:     self.tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')
[rank0]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2032, in from_pretrained
[rank0]:     return cls._from_pretrained(
[rank0]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2272, in _from_pretrained
[rank0]:     tokenizer = cls(*init_inputs, **init_kwargs)
[rank0]:   File "/home/lingyuzeng/project/MolGen/MolGen/model/bart/tokenization_bart.py", line 201, in __init__
[rank0]:     super().__init__(
[rank0]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 439, in __init__
[rank0]:     self._add_tokens(
[rank0]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 547, in _add_tokens
[rank0]:     current_vocab = self.get_vocab().copy()
[rank0]:   File "/home/lingyuzeng/project/MolGen/MolGen/model/bart/tokenization_bart.py", line 235, in get_vocab
[rank0]:     return dict(self.encoder, **self.added_tokens_encoder)
[rank0]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1104, in __getattr__
[rank0]:     raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
[rank0]: AttributeError: BartTokenizer has no attribute encoder. Did you mean: 'encode'?
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/lingyuzeng/project/MolGen/MolGen/generate_ds.py", line 463, in <module>
[rank1]:     runner = Runner(cfgs, writer, logger, rank)
[rank1]:   File "/home/lingyuzeng/project/MolGen/MolGen/generate_ds.py", line 41, in __init__
[rank1]:     self.data_init()
[rank1]:   File "/home/lingyuzeng/project/MolGen/MolGen/generate_ds.py", line 45, in data_init
[rank1]:     self.tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')
[rank1]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2032, in from_pretrained
[rank1]:     return cls._from_pretrained(
[rank1]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2272, in _from_pretrained
[rank1]:     tokenizer = cls(*init_inputs, **init_kwargs)
[rank1]:   File "/home/lingyuzeng/project/MolGen/MolGen/model/bart/tokenization_bart.py", line 201, in __init__
[rank1]:     super().__init__(
[rank1]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 439, in __init__
[rank1]:     self._add_tokens(
[rank1]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 547, in _add_tokens
[rank1]:     current_vocab = self.get_vocab().copy()
[rank1]:   File "/home/lingyuzeng/project/MolGen/MolGen/model/bart/tokenization_bart.py", line 235, in get_vocab
[rank1]:     return dict(self.encoder, **self.added_tokens_encoder)
[rank1]:   File "/home/lingyuzeng/micromamba/envs/molgen/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1104, in __getattr__
[rank1]:     raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
[rank1]: AttributeError: BartTokenizer has no attribute encoder. Did you mean: 'encode'?
[rank0]:[W1217 09:36:24.398842082 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2024-12-17 09:36:26,291] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 2564189
[2024-12-17 09:36:26,292] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 2564190
[2024-12-17 09:36:26,311] [ERROR] [launch.py:325:sigkill_handler] ['/home/lingyuzeng/micromamba/envs/molgen/bin/python3.10', '-u', 'generate_ds.py', '--local_rank=1', '--dist', '1', '--gpu', '1', '--batch_size', '30', '--exp_name', 'generate', '--exp_id', 'qed', '--return_num', '30', '--max_len', '100', '--min_len', '20', '--top_k', '30', '--top_p', '1', '--beam', '30', '--process', 'preprocess', '--generate_mode', 'topk', '--checkpoint_path', '../moldata/checkpoint/molgen.pkl', '--input_path', '../moldata/pretrain/zinc250k.csv', '--output_path', '../moldata/output/candidates.csv', '--finetune_path', '../moldata/output/zinc250k_qed.csv', '--property', 'qed', '--deepspeed', '--deepspeed_config', 'generate_config.json'] exits with return code = 1
```

**Comment by hotwa** [comment]
and, I try to use `../moldata/checkpoint/molgen.pkl`, but in huggingface is bin file. how to get the pkl file? Is safetensors format in this weight?

**Comment by Fangyinfff** [comment]
1. The version we are using is “transformers=4.31.0”. Additionally, please set up the environment following the instructions provided in the README, as there are other dependencies as well.

<img width="967" alt="image" src="https://github.com/user-attachments/assets/fefaf3b5-be36-4b59-940d-3cac604e2bcc" />

2. You can download the model using the following link: https://drive.google.com/drive/folders/1Eelk_RX1I26qLa9c4SZq6Tv-AAbDXgrW?usp=sharing

**Comment by hotwa** [comment]
the MolGen/environment.yml is not correct format，so I can not create the conda enviroment.

**Comment by hotwa** [comment]
and `MolGen/generate_ds.py` do not import nn，need add:

```shell
import torch.nn as nn
```

**Comment by Fangyinfff** [comment]
Hi, 

I have updated another one: https://github.com/zjunlp/MolGen/blob/main/MolGen/environment.yaml

Please try with: `conda env create -f environment.yaml`

**Comment by Fangyinfff** [comment]
> and `MolGen/generate_ds.py` do not import nn，need add:
> 
> ```shell
> import torch.nn as nn
> ```

Thanks, I will revise this.

**Comment by hotwa** [comment]
> Hi,
> 
> I have updated another one: https://github.com/zjunlp/MolGen/blob/main/MolGen/environment.yaml
> 
> Please try with: `conda env create -f environment.yaml`

it's helpful.

**Comment by hotwa** [comment]
in paper, this figure:
![图片1](https://github.com/user-attachments/assets/e4e69fda-3285-4582-8ec1-b1b0e06e1d62)

how to generate? left side figure, how to run in python script?

Is in this repository?

**Comment by Fangyinfff** [comment]
We extract and normalize the attention weights from the final self-attention layer and visualize the attention map for the first three figures. However, we do not provide a Python script for this process. You may reproduce similar visualizations by extracting attention weights and using standard plotting libraries.

**Comment by zxlzr** [comment]
hi, do you have any further questions?
